### ISSUE TITLE
usage of utils, please give an example

### ISSUE THREAD

**Issue by debender495** [GaryB432/gb-generators#27]
Available Generators:

  lerna-typescript
    utils
    classlib
    package
    
For the above generator, please share an example for the utils

**Comment by GaryB432** [comment]
The utils folder is for private functions used internally by the generators.  It should not show in the list of subgenerators because it's not in the generators folder but I don't see a way to remove it.  There is no example of how to use it because it isn't a generator and is not intended for end user invocation.
